// <auto-generated />
namespace Project2MVCApp.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class all_Table_Add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(all_Table_Add));
        
        string IMigrationMetadata.Id
        {
            get { return "201908210625522_all_Table_Add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
